behaviors:
  MoveToTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic: #uczenie przez dostawanie nagrod
        gamma: 0.99
        strength: 0.7
      gail: #uczenie przez nasladownictwo (proba pokonania nauczyciela/zachowania podobnego)
        strength: 0.3 #parametr okresla jak bardzo chcemy by ai nauczylo zachowywac sie jak demonstrator
        demo_path: Demos/MoveDemo.demo #sciezka do pliku demo
    behavioral_cloning: #sekcja okreslajaca jak bardzo ma kopiowac to co robi nauczyciel (nie probuje pokonac go) 
      strength: 0.8 #parametr okresla jak bardzo chcemy by ai nauczylo zachowywac sie jak demonstrator
      demo_path: Demos/MoveDemo.demo #sciezka do pliku demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000